# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [808]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [809]:
# Create a 1-dimensional NumPy array using np.array()
x = np.array([1, 2, 3, 4])

# Create a 2-dimensional NumPy array using np.array()
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Create a 3-dimensional Numpy array using np.array()
z = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [810]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.size)
print(type(x))


(4,)
1
int32
4
<class 'numpy.ndarray'>


In [811]:
# Attributes of 2-dimensional array
print(y.shape)
print(y.ndim)
print(y.dtype)
print(y.size)
print(type(y))

(2, 4)
2
int32
8
<class 'numpy.ndarray'>


In [812]:
# Attributes of 3-dimensional array
print(z.shape)
print(z.ndim)
print(z.dtype)
print(z.size)
print(type(z))

(2, 2, 4)
3
int32
16
<class 'numpy.ndarray'>


In [813]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data_frame = pd.DataFrame(x)
data_frame

0
0  1
1  2
2  3
3  4

In [814]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [815]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [816]:
# Create an array within a range of 0 and 100 with step 3
a = np.arange(0, 100, 3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [817]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
b = np.random.randint(10, size=(7, 2))
b

array([[4, 4],
       [4, 0],
       [0, 2],
       [9, 3],
       [4, 1],
       [7, 1],
       [8, 1]])

In [818]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
c = np.random.rand(3, 5)
c

array([[0.97309775, 0.58011223, 0.25422458, 0.52173005, 0.34265349],
       [0.53224499, 0.12574151, 0.13271465, 0.14354236, 0.93981979],
       [0.73289892, 0.16238189, 0.18834908, 0.73082947, 0.15616384]])

In [819]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
d = np.random.randint(10, size=(4, 6))
d

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [820]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
e = np.random.randint(10, size=(3, 7))
print(e)
# Find the unique numbers in the array you just created
unique = np.unique(e)
print(unique)

[[8 0 9 2 6 3 8]
 [2 4 2 6 4 8 6]
 [1 3 8 1 9 8 9]]
[0 1 2 3 4 6 8 9]


In [821]:
# Find the 0'th index of the latest array you created
print(e[0])

[8 0 9 2 6 3 8]


In [822]:
# Get the first 2 rows of latest array you created
print(e[0:2, :])

[[8 0 9 2 6 3 8]
 [2 4 2 6 4 8 6]]


In [823]:
# Get the first 2 values of the first 2 rows of the latest array
print(e[0:2, 0:2])

[[8 0]
 [2 4]]


In [824]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
f = np.random.randint(10, size=(3, 5))
h = np.ones((3,5))
print(f)
print(h)

[[4 1 3 6 7]
 [2 0 3 1 7]
 [3 1 5 5 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [825]:
# Add the two arrays together
v = f + h
print(v)

[[ 5.  2.  4.  7.  8.]
 [ 3.  1.  4.  2.  8.]
 [ 4.  2.  6.  6. 10.]]


In [826]:
# Create another array of ones of shape (5, 3)
k = np.ones((5, 3))
k

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [827]:
# Try add the array of ones and the other most recent array together
l = k.reshape(v.shape) + v
l

array([[ 6.,  3.,  5.,  8.,  9.],
       [ 4.,  2.,  5.,  3.,  9.],
       [ 5.,  3.,  7.,  7., 11.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [828]:
# Create another array of ones of shape (3, 5)
r = np.ones((3, 5))
r

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [829]:
# Subtract the new array of ones from the other most recent array
l - r

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [830]:
# Multiply the ones array with the latest array
l * r

array([[ 6.,  3.,  5.,  8.,  9.],
       [ 4.,  2.,  5.,  3.,  9.],
       [ 5.,  3.,  7.,  7., 11.]])

In [831]:
# Take the latest array to the power of 2 using '**'
l ** 2

array([[ 36.,   9.,  25.,  64.,  81.],
       [ 16.,   4.,  25.,   9.,  81.],
       [ 25.,   9.,  49.,  49., 121.]])

In [832]:
# Do the same thing with np.square()
np.square(l)

array([[ 36.,   9.,  25.,  64.,  81.],
       [ 16.,   4.,  25.,   9.,  81.],
       [ 25.,   9.,  49.,  49., 121.]])

In [833]:
# Find the mean of the latest array using np.mean()
np.mean(l)

5.8

In [834]:
# Find the maximum of the latest array using np.max()
np.max(l)

11.0

In [835]:
# Find the minimum of the latest array using np.min()
np.min(l)

2.0

In [836]:
# Find the standard deviation of the latest array
np.std(l)

2.5612496949731396

In [837]:
# Find the variance of the latest array
np.var(l)

6.5600000000000005

In [838]:
# Reshape the latest array to (3, 5, 1)
l.reshape((3, 5, 1))

array([[[ 6.],
        [ 3.],
        [ 5.],
        [ 8.],
        [ 9.]],

       [[ 4.],
        [ 2.],
        [ 5.],
        [ 3.],
        [ 9.]],

       [[ 5.],
        [ 3.],
        [ 7.],
        [ 7.],
        [11.]]])

In [839]:
# Transpose the latest array
l.T

array([[ 6.,  4.,  5.],
       [ 3.,  2.,  3.],
       [ 5.,  5.,  7.],
       [ 8.,  3.,  7.],
       [ 9.,  9., 11.]])

What does the transpose do?

In [840]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
m = np.random.randint(10, size=(3, 3))
n = np.random.randint(10, size=(3, 2))
print(m)
print(n)

[[3 5 1]
 [9 1 9]
 [3 7 6]]
[[8 7]
 [4 1]
 [4 7]]


In [841]:
# Perform a dot product on the two newest arrays you created
np.dot(m, n)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [842]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
m = np.random.randint(10, size=(4, 3))
n = np.random.randint(10, size=(4, 3))
print(m)
print(n)

[[9 8 8]
 [0 8 6]
 [8 7 0]
 [7 7 2]]
[[0 7 2]
 [2 0 4]
 [9 6 9]
 [8 6 8]]


In [843]:
# Perform a dot product on the two newest arrays you created
np.dot(m, n)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Users\Options\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Options\AppData\Local\Temp\ipykernel_5140\3834914245.py", line 2, in <module>
    np.dot(m, n)
  File "<__array_function__ internals>", line 200, in dot
ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Options\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 2052, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Options\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structure

It doesn't work. How would you fix it?

In [844]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(m, n.T)

array([[ 72,  50, 201, 184],
       [ 68,  24, 102,  96],
       [ 49,  16, 114, 106],
       [ 53,  22, 123, 114]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [845]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
m = np.random.randint(10, size=(4, 4))
n = np.random.randint(10, size=(4, 4))
print(m)
print(n)

[[7 1 0 6]
 [6 7 4 2]
 [7 5 2 0]
 [2 4 2 0]]
[[4 9 6 6]
 [8 9 9 2]
 [6 0 3 3]
 [4 6 6 3]]


In [846]:
# Compare the two arrays with '>'
m > n

array([[ True, False, False, False],
       [False, False, False, False],
       [ True,  True, False, False],
       [False, False, False, False]])

What happens when you compare the arrays with `>`?

In [847]:
# Compare the two arrays with '>='
m >= n

array([[ True, False, False,  True],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [848]:
# Find which elements of the first array are greater than 7
m > 7

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [849]:
# Which parts of each array are equal? (try using '==')
m == n

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [850]:
# Sort one of the arrays you just created in ascending order
np.sort(m)

array([[0, 1, 6, 7],
       [2, 4, 6, 7],
       [0, 2, 5, 7],
       [0, 2, 2, 4]])

In [851]:
# Sort the indexes of one of the arrays you just created
np.argsort(m)

array([[2, 1, 3, 0],
       [3, 2, 0, 1],
       [3, 2, 1, 0],
       [3, 0, 2, 1]], dtype=int64)

In [852]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(m, axis=0)

array([0, 1, 1, 0], dtype=int64)

In [853]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(m, axis=0)

array([3, 0, 0, 2], dtype=int64)

In [854]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(m, axis=1)

array([0, 1, 0, 1], dtype=int64)

In [855]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(m, axis=0)

array([3, 0, 0, 2], dtype=int64)

In [856]:
# Create an array of normally distributed random numbers
i = np.random.normal(0, 0.1, 20)
i

array([ 0.01357538,  0.06080897,  0.07049813,  0.03609234, -0.14669679,
        0.08926295, -0.01052571, -0.09553464, -0.04147646, -0.13987409,
       -0.03440805,  0.07507859, -0.03276252, -0.08615981, -0.02581848,
        0.04609556, -0.134939  , -0.10190728,  0.01270122, -0.12494437])

In [857]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.